### PR TITLE
Cache xmake using @actions/cache

### PR DESCRIPTION
**Pull request by ZhUyU1997**
- Add a new configuration field to control the cache folder.
 If not set, still use @actions/tool-cache as before
   > Feature Request: #16 
  
  Usages:
  ```yaml
              - uses: xmake-io/github-action-setup-xmake@v2
                with:
                    xmake-version: "2.7.2"
                    actions-cache-folder: ".xmake-cache"
  ```
-  The node_modules folder will be very large if we add @actions/cache. 
   To solve it, I ignore it and build using "ncc". It is also a good practice for maintenance.

### CODE REVIEW

**Comment by waruqi** [comment]
do not remove dist and node_modules dirs

**Comment by ZhUyU1997** [comment]
> do not remove dist and node_modules dirs

node_modules  should be removed for better maintainability. 
We can bundle with the library to remove dependency on node_modules.
Can you explain more about why keep it?

**Comment by ZhUyU1997** [comment]
The test of action is passed in my repository. https://github.com/ZhUyU1997/github-action-setup-xmake/actions. Can you trigger it on this PR?

**Comment by waruqi** [comment]
ok, I have merged it, thanks!

**Comment by qudix** [comment]
I have to say, the configuration name made me believe it had something to do with package caching, but this is for the tool itself. Something like `actions-tool-cache-folder` would make it a bit more clearer.

**Pull request merged**
