### PR TITLE
Upgrade Node.js to 20

### PR DESCRIPTION
**Pull request by futrime**
Upgrade Node.js to 20

### CODE REVIEW

**Comment by waruqi** [comment]
try add `yarn config set "strict-ssl" false -g` on ci?

**Comment by OpportunityLiu** [comment]
Thank you for your contribution.

**Comment by waruqi** [comment]
@OpportunityLiu It's still node16 now. 

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20:

**Comment by OpportunityLiu** [comment]
That is one of our dependency's dependency, which is only used in building.

**Pull request closed without merging**
